### ISSUE TITLE
小米mix2 android9   demo apk 测试返回  闪一下

### ISSUE THREAD

**Issue by wangyuan0217** [gongwen/SwipeBackLayout#17]
demo apk安装测试，操作滑动返回后，页面会重新再有个从上到下消失的闪屏效果

**Comment by Liar1995** [comment]
![image](https://user-images.githubusercontent.com/13048201/68185016-76595f00-ffdb-11e9-9b7f-c16bb1423d1f.png)
同样的问题，设置方向为Top，下拉关闭以后，会有动画的残影闪一下，从上到下

**Comment by gudd1991116** [comment]
你们闪一下的问题解决了么，我只有在横屏的时候退出时会闪一下呢！

**Comment by ChinaZeng** [comment]
请问解决了吗？

**Comment by ChinaZeng** [comment]
我这边在我自己项目中有了解决
`
/**
 * 解决滑动结束后，finish过程中还设置view可见或者隐藏等触发onLayout出现闪屏的bug
 */
public class SuperSwipeBackLayout extends SwipeBackLayout {
    public SuperSwipeBackLayout(@NonNull Context context) {
        this(context, null);
    }

    public SuperSwipeBackLayout(@NonNull Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public SuperSwipeBackLayout(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        if (isFinish) {
            return;
        }
        super.onLayout(changed, l, t, r, b);
    }


    private boolean isFinish = false;

    @Override
    public void finish() {
        isFinish = true;
        super.finish();

    }
}
`

**Comment by ChinaZeng** [comment]
我在我的项目如下解决：
```java
/**
 * 解决滑动结束后，finish过程中还设置view可见或者隐藏等触发onLayout出现闪屏的bug
 */
public class SuperSwipeBackLayout extends SwipeBackLayout {
    public SuperSwipeBackLayout(@NonNull Context context) {
        this(context, null);
    }

    public SuperSwipeBackLayout(@NonNull Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public SuperSwipeBackLayout(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        if (isFinish) {
            return;
        }
        super.onLayout(changed, l, t, r, b);
    }


    private boolean isFinish = false;

    @Override
    public void finish() {
        isFinish = true;
        super.finish();

    }
}

```
