### ISSUE TITLE
效果挺好， 就是老项目中接入成本太高了

### ISSUE THREAD

**Issue by yanxinmiao** [gongwen/SwipeBackLayout#3]

**Comment by gongwen** [comment]
成本怎么高？

**Comment by yanxinmiao** [comment]
不得修改每个页面的根布局 ？

**Comment by gongwen** [comment]
不用修改，你可以这么用
public void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    View contentView = LayoutInflater.from(this).inflate(resource, null, false);
    SwipeBackLayout mSwipeBackLayout = new SwipeBackLayout(this);
    mSwipeBackLayout.addView(contentView);
    setContentView(mSwipeBackLayout);
}

**Comment by yanxinmiao** [comment]
这个写和改动xml文件效果一样，把布局的根布局换成SwipeBackLayout， 但是每个Activity 都要这么改 吧

**Comment by gongwen** [comment]
可以抽象出基类，做最少的改动，
public abstract class BaseSwipeActivity extends BaseActivity {
    protected SwipeBackLayout mSwipeBackLayout;

    public abstract int getLayoutId();

    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(getLayoutId());
        mSwipeBackLayout = new SwipeBackLayout(this);
        mSwipeBackLayout.attachToActivity(this);
    }
}
